### PR TITLE
Username validation disabled

### PR DESCRIPTION
**Pull request by diasjorge**

### CODE REVIEW

**Comment by diasjorge** [comment]
This pull request builds on top of the previous one but also adds support to disable user validation entirely if that were to be accepted

**Comment by russell-lewis** [comment]
Thanks for the PR related to https://github.com/Netflix/bless/issues/25 
I'm not sure I see a use case for the relaxed validation.

If we moved the various validation functions from being static to class methods, we could set a context for a schema instance and use that to control which validation is used, instead of relying on a global variable.

Recently I made some changes to how remote_usernames were validated as well.  I think we could enable configuration of how that is validated as well.

I'll close PR#24, and I will have time early next week to enhance this PR if you don't beat me to it.

**Comment by diasjorge** [comment]
I've implemented the validations using context, I think it's cleaner now without using global variables. I hope this is aligned with what you had in mind.
BTW if you want to merge #45 first I could then rebase on top of that.

**Comment by diasjorge** [comment]
Rebased on top of master

**Comment by diasjorge** [comment]
@russell-lewis have you had a chance to revisit this issue?

**Comment by russell-lewis** [comment]
@diasjorge take a look at https://github.com/diasjorge/bless/pull/1 when you have a chance.

**Comment by diasjorge** [comment]
Funny thing I didn't see the notification as I wasn't expecting you to make a PR against my PR :)

**Pull request merged**
